import Head from "next/head";
import { Inter } from "@next/font/google";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillTwitterCircle, AiFillLinkedin } from "react-icons/ai";
import { RiWhatsappFill } from "react-icons/ri";
import Image from "next/image";
import Enoch from "../../public/Enoch.png";
import myimage from "../../public/myimage.png";
import deved from "../../public/dev-ed-wave.png";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Enoch Chirima</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10">
        <section className="min-h-screen">
          {/* Navigation */}
          <nav className="py-10 flex justify-between">
            <h1 className="text-xl font-burtons">Developed by</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-4"
                  href=""
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          {/* Hero */}
          <div className="text-center p-10">
            <h2 className="text-teal-600 text-5xl font-medium">
              Enoch Chirima
            </h2>
            <h3 className="text-2xl py-2">Software Developer</h3>
            <p className="text-md py-5 leading-8 text-gray-800">
              "Welcome to my portfolio! As a full-stack software developer, I
              specialize in creating intuitive and functional web applications
              that solve real-world problems. With expertise in both front-end
              and back-end development, I have the flexibility to take on a wide
              range of projects, from designing responsive user interfaces to
              building powerful APIs. Whether you're looking for a freelance
              developer or seeking to hire a full-time team member, I'm here to
              help. Take a look at my work and let's chat about how I can bring
              my skills and experience to your next project!"
            </p>
          </div>
          <div className=" text-5xl flex justify-center gap-16 py-3 text-gray-900">
            <AiFillLinkedin />
            <AiFillTwitterCircle />
            <RiWhatsappFill />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 w-80 h-80 rounded-lg">
            <Image src={Enoch} />
          </div>
        </section>
        {/* Tools */}
        <div className="">
          <div className=""></div>
        </div>
       
      </main>
    </>
  );
}




{/* <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
<div class="col-span-1 md:col-span-2 lg:col-span-1 bg-gray-200">
  Item 1
</div>
<div class="col-span-1 md:col-span-2 lg:col-span-1 bg-gray-300">
  Item 2
</div>
<div class="col-span-1 md:col-span-2 lg:col-span-1 bg-gray-400">
  Item 3
</div>
<div class="col-span-1 md:col-span-2 lg:col-span-1 bg-gray-500">
  Item 4
</div>
</div> */}
